### PR TITLE
Touch bundles affected by the new ecj version

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184

### CODE REVIEW

**Comment by iloveeclipse** [comment]
PR fails while generating javadoc for "ResourceBundleHelper".
```
MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /home/jenkins/agent/workspace/eclipse.platform.ui_PR-901/tools/bundles/org.eclipse.e4.tools.services/src/org/eclipse/e4/tools/services/impl/ResourceBundleHelper.java:56: error: unexpected end tag: </p>
	 * </p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-901/tools/bundles/org.eclipse.e4.tools.services/src/org/eclipse/e4/tools/services/impl/ResourceBundleHelper.java:69: error: unexpected end tag: </p>
	 * </p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-901/tools/bundles/org.eclipse.e4.tools.services/src/org/eclipse/e4/tools/services/impl/ResourceBundleHelper.java:142: error: unexpected end tag: </p>
	 * </p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-901/tools/bundles/org.eclipse.e4.tools.services/src/org/eclipse/e4/tools/services/impl/ResourceBundleHelper.java:155: error: unexpected end tag: </p>
	 * </p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-901/tools/bundles/org.eclipse.e4.tools.services/src/org/eclipse/e4/tools/services/impl/ResourceBundleHelper.java:192: error: unexpected end tag: </p>
	 * </p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-901/tools/bundles/org.eclipse.e4.tools.services/src/org/eclipse/e4/tools/services/impl/ResourceBundleHelper.java:205: error: unexpected end tag: </p>
	 * </p>
	   ^
6 errors
```

This is unrelated to the current PR and caused by https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1189

I will try to fix that.

**Comment by akurtakov** [comment]
Sorry that you faced it first but I'm happy to see we catch more and more things in verification builds to not allow such things to enter the codebase anymore.

**Comment by iloveeclipse** [comment]
One test fail in
```
java.lang.NullPointerException
	at java.base/java.util.Comparator.lambda$comparingInt$7b0bb60$1(Comparator.java:494)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at org.eclipse.ui.genericeditor.tests.FoldingTest.lambda$0(FoldingTest.java:87)
	at org.eclipse.ui.tests.harness.util.DisplayHelper$2.condition(DisplayHelper.java:254)
	at org.eclipse.ui.tests.harness.util.DisplayHelper.waitForCondition(DisplayHelper.java:237)
	at org.eclipse.ui.tests.harness.util.DisplayHelper.waitForCondition(DisplayHelper.java:269)
	at org.eclipse.ui.genericeditor.tests.FoldingTest.assertFoldingAsync(FoldingTest.java:83)
	at org.eclipse.ui.genericeditor.tests.FoldingTest.testCustomFoldingReconciler(FoldingTest.java:63)
```

**Comment by iloveeclipse** [comment]
Just curious, does such code like added in bb5b98a413b3cf148204d5c01049adc9a7731207 **really** improves the test? Looking on the fail above it is nearly impossible to find the root cause...
